spring.application.name=drug-inventory

spring.datasource.url=jdbc:mysql://localhost:3306/drug_inventory_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Praga@648

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080
jwt.secret=drug_inventory_super_secret_key_2024_pharma_system
jwt.expiration=86400000